src/Entity/Interaction.php
<?php

namespace App\Entity;

use App\Repository\InteractionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InteractionRepository::class)
 */
class Interaction
{
    public const LIKE = 0;
    public const SHARE = 1;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $interaction_type;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="interactions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="interactions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInteractionType(): ?int
    {
        return $this->interaction_type;
    }

    public function setInteractionType(int $interaction_type): self
    {
        $this->interaction_type = $interaction_type;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\ArticleSearch;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Form\SearchForm;
use DateTime;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="default")
     */
    public function index(ArticleRepository $articleRepository, Request $request): Response
    {
        $data = new ArticleSearch();
        $data->page = $request->get('page', 1);
        $form = $this->createForm(SearchForm::class, $data);
        $form->handleRequest($request);
        $articles = $articleRepository->findSearch($data);

        $user = $this->getUser();
        if ($user) {
            $articles = $user->getArticles()->toArray();
            foreach ($articles as $article) {
                $tabArticles[] = $article->getId();
            }
        }


        return $this->render('default/home.html.twig', [
            'articles' => $articles,
            'form' => $form->createView(),
            'user_article' => isset($tabArticles) && $tabArticles ? $tabArticles : null,
        ]);
    }

    /**
     * @Route("/propos", name="propos")
     */
    public function propos(): Response
    {
        return $this->render('default/propos.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
    }

    /**
     * @Route("/", name="default_home", methods={"GET"})
     */

    public function home(PaginatorInterface $paginator, Request $request, ArticleRepository $articleRepository): Response
    {
        $donnees = $this->getDoctrine()->getRepository(Article::class)->findBy([], ['creationDate' => 'desc']);
        $articles = $paginator->paginate(
            $donnees,
            $request->query->getInt('page', 1),
            5
        );

        $user = $this->getUser();
        if ($user) {
            $articles = $user->getArticles()->toArray();
            foreach ($articles as $article) {
                $tabArticles[] = $article->getId();
            }
        }

        return $this->render('default/home.html.twig', [
            'articles' => $articles,
            'user_article' => isset($tabArticles) && $tabArticles ? $tabArticles : null,
        ]);
    }

    /**
     * @Route("/detail/{id}", name="default_show", methods={"GET"})
     */
    public function show(Article $article, Request $request, EntityManagerInterface $manager): Response
    {

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        $comment->setDate(new DateTime());

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setDate(new \DateTime())
                ->setArticle($article);
            $manager->persist($comment);
            $manager->flush();

            return $this->redirectToRoute('default_show', ['id' => $article->getId()]);
        }
        return $this->render('default/show.html.twig', [
            'article' => $article,
            'Form' => $form->createView()
        ]);
    }
}

templates/default/home.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
	<link rel="stylesheet" href="/css/bootstrap.min.css">
	<link href="{{ asset('css/article/home.css') }}" rel="stylesheet"/>
{% endblock %}
{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-3" style='border: 5px; padding: 20px; background-color: #3B5145;'>
				<h3 style="color: white;">Recherche</h3>

				{# 
																																																																																																																										{{ form_start(form, {attr: {class: 'filter js-filter-form'}}) }} 
																																																																																																																										<div class="spinner-border js-loading" role="status" aria-hidden="true" style="display: none">
																																																																																																																										<button type="submit" class="btn btn-primary w-100">Filtrer</button>
																																																																																																																										{{ form_end(form) }} 
																																																																																																																								#}
			</div>

			<div class="col-9" style='border: 5px; padding: 20px; background-color: #D5F5E3;'>
				<section class="articles">
					{% for article in articles %}
						<hr>
						<article>

							{#{% if article.id in user_article  %}																							<a class="link" href="{{path('article_edit', {'id': article.id})}}">
																																																																																																																																													{% else %}#}
							<a
								class="link" href="{{path('article_show', {'id': article.id})}}">
								{#{% endif %}#}
								<h5>{{article.title}}</h5>
							</a>
							<h5>{{article.subtitle}}</h5>
							<div class="metadate">Ecrit le
								{{article.creationDate | date('d/m/Y')}},
								{% if article.autor != null  %}
									by
									{{article.autor.firstname}}
									{{article.autor.lastname}}
								{% else %}
									by unknown user
								{% endif %}
								à
								{{article.creationDate | date('H:i')}},
														Categorie:
								{{article.category.name}}
							</div>
							<div class="row">
								<div class="col-md-3">
									<img src='{{article.picturePath}}' , style="width:200px;height:130px;">
								</div>
								<div class="col-md-9">
									{{article.content | raw}}
									{# <a href="{{path('default_show', {'id': article.id})}}" class="btn btn-outline-info">... Lire la suite</a> #}
								</div>
							</div>
							<div class="socials">
								<div onclick="interact({{article.id}} , {{ app.user != null? app.user.id : 'null' }} , 0 , this )" class="social" ">
									<span class=" social_tag">
										{{ article.interactions |filter(v => v.interactionType == 0 )|length }}
										{# an error with   constant('App\\Entity\\Article::LIKE')) |length  }}     #}
									</span>
									<svg class="social_icon">
										<use xlink:href="#like"></use>
									</svg>
								</div>
								<div onclick="interact({{article.id}} , {{ app.user != null? app.user.id : 'null' }} , 1 ,this )" class="social">
									<span class="social_tag">
										{{ article.interactions |filter(v => v.interactionType == 1 )|length }}
										{# an error with   constant('App\\Entity\\Article::LIKE')) |length  }}     #}
									</span>
									<svg class="social_icon">
										<use xlink:href="#comment"></use>
									</svg>
								</div>
							</div>
						</article>
					{% endfor %}
				</section>
			</hr>
			{# <div class="pagination float-center"> 
																																																																																																																																																																																		 {{knp_pagination_render(articles)}}
																																																																																																																																																																																		</div> #}
		</div>
		<div id="myModal" class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLongTitle">Espace Reservé</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<div class="row w-100 d-flex flex-column">
							<div class="col-12">
								<img class="w-100" src="{{ asset('images/social.jpg') }}" alt="Symfony!"/>
							</div>
							<div class="">
								vous êtes nouveaux parmis nous rejoignez nous via les bouton ci-dessous
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button class="btn btn-secondary" data-dismiss="modal">Close</button>
						<a href="{{path('app_login')}}" class="btn btn-primary">Se connectez</a>
						<a href="#" class="btn btn-primary">Nous Rejoindre</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
		async function interact(article_id, user_id, interactionType, element) {

console.log(element);
number = Number.parseInt(element.children[0].innerText);

var url = Routing.generate('article_interact', {'id': article_id});

let content = {
user: user_id,
interact_type: interactionType
};

if (user_id != null) {

let response = await fetch(url, {
method: "POST",
body: JSON.stringify(content)
});

liked = await response.json();
if (liked['action'] == 'add' && liked['state'] == true) {
number += 1;
} else if (liked['action'] == 'remove' && liked['state'] == true) {
number -= 1;
}
element.children[0].innerText = number;
} else {
$("#myModal").modal()
}

}
	</script>
</div>{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}

	<div>
		<h5>Les derniers articles</h5>
	</div>
{% endblock %}

templates/default/propos.html.twig
{% extends 'base.html.twig' %}

{% block title %}FJT-BLOG {% endblock %}

{% block body %}


<div class="container" style='border: 5px; padding: 20px; background-color: #D5F5E3;' >
    <center> <h4> BIENVENUE SUR BLOG FJT ✅</h4>

   {# <img src="https://www.periwinkle.fr/wp-content/uploads/2017/09/equipe_slider.png?x33745", style="width:550px;height:300px;"/> #}
   <img src="https://neilpatel.com/wp-content/uploads/2018/10/blog.jpg", style="width:550px;height:300px;"/>

<p> RAMON Antonin - SAEZ Dorian - Thanh NGUYEN - AMGHAR Axel</p>

   </center>
   <hr>

<div class="row">
   <div class="col-4">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos veniam voluptate eaque laborum quidem laboriosam nihil alias dolores, animi, maxime ipsa suscipit! Temporibus inventore fugiat neque. Repellat doloremque commodi nihil?</p>
    </div>
    <div class="col-4">
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla officia neque reiciendis ipsa expedita adipisci! Fugiat animi incidunt hic aliquam, odit sapiente placeat, eos accusantium esse ratione soluta aspernatur asperiores.</p>
    </div>
    <div class="col-4">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis veniam alias provident natus, assumenda nostrum vel nihil cum! Sint aliquid aliquam ex libero vitae? Rerum quaerat labore nostrum neque praesentium?</p>
    </div>
</div>
</div>
{% endblock %}

templates/default/show.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <article>
        <h2>{{article.title}}</h2>
        <div class="metadate">Ecrit le {{article.creattionDate | date('d/m/Y')}} à {{article.creattionDate | date('H:i')}} dans la category {{article.category.name}}</div>
        <div class="content">
            <img src="{{article.image}}" alt="">
            <br>
            {{article.content | raw}}
         </div>
    </article>
     <section id="commentaire">
        <h3> {{article.comments | length}} Commentaires</h3>
        {% for comment in article.comments %}
            <div class="comment">
                <div class="row">
                    <div class="col-3">
                  <small>{{comment.Date | date('d/m/Y à H:i')}}</small>)
                    </div>

                    <div class="col">
                    {{comment.content | raw}}
                    </div>
                </div>
            </div>
        {% endfor %}

{# {% if app.user %} #}
        {# {{form_start(Form)}}
            {{form_row(Form.user, {'attr': {'placehold':'Votre nom'}})}}
            {{form_row(Form.content, {'attr': {'placehold':'Votre commentaire'}})}}
             <button type="submit" class="btn btn-success"> Send</button>
            {{form_end(Form)}}  #}
{# {% else %} #}
<h4> Attention: Vous ne pouvez pas commenter si vous ne vous authentifiez pas sur le site ! </h4>

{% endif %}
    </section>

{% endblock body %}